version: '2.1'

services :

  #############################################################################
  # Mock S3
  static_assets :
    image          : scality/s3server:latest
    container_name : s3
    mem_limit      : 512m
    ports          :
    - "${AWS_S3_PORT}:8000"
    volumes        :
    - "./tmp/env/${NODE_ENV}/mocks3/buckets/main/data:/usr/src/app/localData:cached"
    - "./tmp/env/${NODE_ENV}/mocks3/buckets/main/meta:/usr/src/app/localMetadata:cached"
    - "./run/env/${NODE_ENV}/mocks3/config.json:/usr/src/app/conf/config.json"
    - "./run/env/${NODE_ENV}/mocks3/locationConfig.json:/usr/src/app/conf/locationConfig.json"

  #############################################################################
  # Redis
  cache :
    image          : redis:4.0.2-alpine
    container_name : redis
    mem_limit      : 256m
    command        : ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports          :
    - "${REDIS_PORT}:6379"
    volumes        :
    - "./tmp/env/${NODE_ENV}/redisdata:/data:cached"
    - "./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  #############################################################################
  # MySQL
  database :
    image          : seancannon/dev_mysql
    hostname       : mysql
    container_name : mysql
    mem_limit      : 512m
    environment    :
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
      - "TZ=${CORE_DB_TIMEZONE}"
    volumes        :
      - "${MYSQL_VOLUME_MOUNT}"
    tmpfs          :
      - "${MYSQL_TMPFS}"
    ports          :
      - "${CORE_DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "--password=${CORE_DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
    command: mysqld --max_allowed_packet=64M

  #############################################################################
  # PHPMyAdmin
  dbgui :
    image          : phpmyadmin/phpmyadmin:4.9
    container_name : phpmyadmin
    mem_limit      : 4092m
    environment    :
      - "MYSQL_USERNAME=${CORE_DB_USER}"
      - "MYSQL_ROOT_PASSWORD=${CORE_DB_ROOT_PASSWORD}"
      - "UPLOAD_LIMIT=3000000000"
    links          :
      - database:db
    ports          :
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "./tmp/env/${NODE_ENV}/phpmyadmin/sessions:/sessions"
    depends_on:
      database:
        condition: service_healthy
